name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: eeems/remarkable-toolchain:latest-rm2

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y zip curl build-essential qt6-base-dev qt6-tools-dev qt6-declarative-dev qt6-base-private-dev libts-dev

    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install
        sh install -y
        rm install
        . "$HOME/.cargo/env"
        rustup target add armv7-unknown-linux-gnueabihf

    - name: Clone xovi
      run: git clone https://github.com/asivery/xovi /tmp/xovi

    - name: Build plugin
      run: . /opt/codex/rm2/*/environment-setup-cortexa7hf-neon-remarkable-linux-gnueabi && qmake && make

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libqevdevlamyplugin
        path: |
          *.so
          *.a
